#!/bin/bash

OGsrc=$(ls /home/pieter/pipeline/src/*)

for file in $OGsrc
do

    NEWsrc=$(echo ${file} | awk -F/ '{print $NF}')

    sed "s/\$LOC\.\.\/install_locations/\"\$LOC\"install_locations/g" ${file} > $NEWsrc

done
